development:
  ethnicchic:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: spree_ethnicchic_old
    pool: 5
    username: root
    password:
    socket: /var/run/mysqld/mysqld.sock