source 'http://rubygems.org'

group :development do
  gem 'guard'
  gem 'guard-rspec'
  gem 'rb-inotify', :require => false
  gem 'rb-fsevent', :require => false
  gem 'rb-fchange', :require => false
  gem 'listen'
  gem 'libnotify'
  gem 'byebug'
end

group :test do
  gem 'rspec-rails'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'nokogiri'
  gem 'capybara'
  gem 'faker'
  gem 'factory_girl'
end

gemspec
